fix(common): proxy not working on different protocol to downloadUrl
tinesoft/nxrocks pull request #162
Opened 2023-03-29 06:56 UTC by Darkterror45

fixes #158

2023-03-31 10:58 UTC, tinesoft commented on packages/common/src/lib/core/utils/utils.ts
> +export function getHttpProxyAgent(proxyUrl?: string, downloadUrl?: string): HttpProxyAgent | HttpsProxyAgent | undefined {
can you please make `downloadUrl`  **not optional** (and so move it _before_  `proxyUrl` ?   as such:

```
export function getHttpProxyAgent(downloadUrl: string, proxyUrl?: string, ): HttpProxyAgent | HttpsProxyAgent | undefined {
```

2023-03-31 11:02 UTC, tinesoft commented on packages/common/src/lib/core/utils/utils.ts
> +  if (downloadUrl?.startsWith('https')) {
change the condition to:
```
  if (targetUrl.startsWith('https')  && !!proxyUrl) {
```

(_only set the proxy if needed (proxyUrl  is truthy)_)

2023-03-31 11:03 UTC, tinesoft commented on packages/common/src/lib/core/utils/utils.ts
> +  } else if(downloadUrl?.startsWith('http')){
change the condition to:
```
  if (targetUrl.startsWith('http')  && !!proxyUrl) {
```

(_only set the proxy if needed (proxyUrl  is truthy)_)

2023-03-31 11:04 UTC, tinesoft commented on packages/common/src/lib/core/utils/utils.ts
> +export function getCommonHttpHeaders( pkgName: string, proxyUrl?: string, downloadUrl?: string){
can you please : 
- make `downloadUrl`  **not optional**,
- rename it into a more generic `targetUrl` 
- and so move it _before_  `proxyUrl`
- 
as such:

```
export function getCommonHttpHeaders( pkgName: string, targetUrl?: string, proxyUrl?: string){
```

2023-03-31 11:05 UTC, tinesoft commented on packages/nx-micronaut/src/utils/micronaut-utils.ts
> +    const response = await fetch(`${options.micronautLaunchUrl}/application-types/${options.projectType}/features`, getCommonHttpHeaders(NX_MICRONAUT_PKG, options.proxyUrl, options.micronautLaunchUrl
swap parameters of "getCommonHttpHeaders" based on previous refactoring

2023-03-31 11:06 UTC, tinesoft commented on packages/nx-spring-boot/src/generators/project/lib/generate-boot-project.ts
> +    const response = await fetch(downloadUrl, getCommonHttpHeaders(NX_SPRING_BOOT_PKG, options.proxyUrl, downloadUrl));
swap parameters of "getCommonHttpHeaders" based on previous refactoring

2023-03-31 11:06 UTC, tinesoft commented on packages/nx-quarkus/src/utils/quarkus-utils.ts
> +    const response = await fetch(`${options.quarkusInitializerUrl}/api/extensions`, getCommonHttpHeaders(NX_QUARKUS_PKG, options.proxyUrl, options.quarkusInitializerUrl));
swap parameters of "getCommonHttpHeaders" based on previous refactoring

2023-03-31 11:07 UTC, tinesoft requested changes
Thank you for the PR!

Can you address the changes suggested please?
I'll merge afterwards if validated

2023-04-04 10:36 UTC, tinesoft commented
Hi @Darkterror45 

Did you have time to apply the requested changes?

If not, and if you don't mind, I'll take over and continue the PR (you'll still be the author of course ^^).

I'm asking because I'd like to release this before the end of the week if possible.

Thanks!

2023-04-04 11:26 UTC, Darkterror45 commented
Hi @tinesoft,

Yes, i have push the requested changes.

2023-04-05 02:10 UTC, merged

2023-04-05 02:13 UTC, tinesoft commented
Thanks for the PR @Darkterror45 ! 🙏🏾